apiVersion: v1
kind: Service
metadata:
  name: stackit-ai-backend
  labels:
    app: stackit-ai-backend
spec:
  selector:
    app: stackit-ai-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
