apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackit-ai-frontend
  labels:
    app: stackit-ai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackit-ai-frontend
  template:
    metadata:
      labels:
        app: stackit-ai-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/godsup/stackit-ai-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
